### ISSUE TITLE
Server draw lost message when "Use 32-bit vertex indices"

### ISSUE THREAD

**Issue by Eragon-Brisingr** [sammyfreg/netImgui#17]
**Describe the bug**

**To Reproduce**
1. cancel annotation ‘#define ImDrawIdx unsigned int’ in imconfig.h both in netImgui and UnrealImGui.
2. compile this project and run.
3. draw over ten thousand circle in imgui.
4. server seem like not execute draw all circle.

**Expected behavior**
server behavior same like local

**Screenshots**
![NetImguiServerError](https://user-images.githubusercontent.com/16950908/126042639-695ab667-e2cc-459d-8755-e0cacf6ab70a.png)
![NetImguiServerErrorGIF](https://user-images.githubusercontent.com/16950908/126043042-405c719b-70e7-4d03-a8f4-bfa0275c869d.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [netImgui 1.5]

**Additional context**
Thank you upgrade UnrealImGui to netImgui 1.5! I want draw meta world all entity location (count will over ten thousand). But  looks like remote server can't draw so many graphics.

**Comment by sammyfreg** [comment]
Fixed in submit b1016ac. 

**Note 1:** The server application doesn't need to be rebuilt to match your Dear Imgui Index size anymore. It now handles both 16/32bits indices.

**Note 2:** You don't need to compile Dear ImGui with 32bits index to handle large amount of content. ImGui automatically split large amount of vertices into multiple drawcalls (+ vertex offset)

**Note 3:** I added 2 samples to test this large amount of content problem (SampleIndex16, SampleIndex32). Thank you for bringing this to my attention.

**Note 4:** UnrealImgui's pull request has been also updated with this change. This means you should be able to get it and run with the NetImguiServer application as it, without needing to recompile it (whether you choose to use 16 or 32 bits indices).
