### ISSUE TITLE
Supporting multiple imgui contexts in the same app

### ISSUE THREAD

**Issue by Skylark13** [sammyfreg/netImgui#23]
Hello,

In our app, we have multiple imgui contexts at the same time, because we have separate game and rendering threads which can call imgui. When using NetImgui, the result is that only the commands sent to one of the contexts are shown in the remote viewer (the context which was current when NetImgui::Connect* was called, since that's the context to which the hooks were added).

Is there a way you had envisioned supporting this? I can tell you what I have, but I'm not sure that's how it should work, ideally.

So what I did was to call NetImgui::Connect* for both contexts. This gives me two client windows in the remote viewer, which is not ideal. So I made some changes to the remote viewer so that when the connection client name (client.mInfoName) is the same for two connections, they both use the same client instance (and then I had to make changes so that a single client can have multiple imgui draw data, one for each connection). And finally, when rendering the imgui draw data, I made it clear the texture only for the first one. These changes have no effect if there is only one connection per client, of course.

If you're interested I can send a patch with these changes. But I'd be interested to know what the ideal solution would look like in your opinion.

**Comment by sammyfreg** [comment]
My first question is, are the 2 contexts supposed to be visible at the same time? 

If both are active, it means that the same input is sent to both? And since they each generates their own draws, one context is always rendered in top of the other one? If this is the case, I'd have to give it some thoughts.

If it's the alternative of only having 1 context active at a time, with a way to switch between them, then this can be handled without changes. In fact, the Unreal ImGui plugin does this, it has multiple contexts and when connected with NetImgui, allows users to chose which context should be send for remote rendering.

**Comment by Skylark13** [comment]
Both contexts are active at the same time. Yes, inputs are sent to both. For the rendering, I'm not sure, because I noticed that windows don't overlap the same way in our engine as they do in the remote viewer, so there must be some ordering issue. I'll investigate more on Monday. My implementation is not perfect for sure, but I did it as a starting point to see if it was possible.

**Comment by sammyfreg** [comment]
Hmmm, that's pretty unusual, having 2 contexts processing the same inputs and rendering to the same output.

How does it even handle having a valid window around same location of both context, to determine who gets the mouse click input?

**Comment by ocornut** [comment]
As I've been directed to this topic today,

> If both are active, it means that the same input is sent to both? And since they each generates their own draws, one context is always rendered in top of the other one? If this is the case, I'd have to give it some thoughts.
> If it's the alternative of only having 1 context active at a time, with a way to switch between them, then this can be handled without changes. In fact, the Unreal ImGui plugin does this, it has multiple contexts and when connected with NetImgui, allows users to chose which context should be send for remote rendering.

IMHO the possible levels of support are:

- (1) increase visibility on the fact that it is easy to switch between two contexts. Apparently it is already supported, but I would assume in practice it needs to be well understand and maybe possible to mapped to a shortcut (e.g. F1/F2) for instance switch. Maybe this is already the case, sorry that I don't know.

- (2) render both, with the selected context on top, but only ever send input to selected context. If people frequently have simultaneous output from update/render or e.g. client/server it may be nice to see both EVEN if you can't interact with both.

- (3) render both and dispatch inputs smartly (this is more work). 

For (3),  There is a helper called `imgui_multicontext_compositor`:
https://github.com/ocornut/imgui_club/tree/main/imgui_multicontext_compositor

"
When using and displaying multiple contexts simultaneously (e.g. Update vs Rendering domains):
- Manage z-order of contexts
- Manage input routing
- Allow drag and drop between contexts

"
![multi_context_compositor.gif](https://github.com/user-attachments/assets/220a9469-db15-419a-8f29-3e0bf7025c84)

This was designed to be used locally but I would assume it could be adapted to a viewer like netImGui.

Anyhow, even if just (1) and (2) are supported (and are easy) I imagine users of multiple contexts would have a better experience.
Then (3) is arguably more work but users of (2) may naturally attempt to integrate it.

**Comment by sammyfreg** [comment]
For (1) it's not that NetImgui supports multiple context per say, it's that the library user can use a dedicated context for the remote connexion and re-route the Imgui drawing commands of a 'selected scenario' context to it. That's how it's done in UnrealImGui plugin at the moment, with an entry in the main menu that let user to pick which 'view' to override.

For (2), NetImgui currently only support one connection per client, with 1 Imgui context. I would need to engineer a way to intercept multiple context, instead of a single one, and somehow send 1 drawdata? Or multiple draw data for the same client, but displayed over each other? I'm not sure yet how this could be done cleanly without complicating the codebase too much. And this still doesn't address dispatching the inputs 'smartly' (This might be do-able by having 1 active context to get all inputs, except mouse click that can change which context is active).
