### ISSUE TITLE
Cmake build system

### ISSUE THREAD

**Issue by lemantisee** [sammyfreg/netImgui#32]
Hello. It's possible to add cmake build system to project? Cmake can helps to build NetImGui on Linux and makes possible to work in different IDE's.

**Comment by sammyfreg** [comment]
I'm using 'Sharpmake' to create my VS solutions. It also could also export
gnu makefile with a few tweaks, but haven't tried to do it yet.

https://github.com/ubisoft/Sharpmake

**Comment by lemantisee** [comment]
Thanks. I will try to generate makefile.

And what about support of another IDE's? Such as CLion or QtCreator. Or that suppose to be on fork side?

**Comment by sammyfreg** [comment]
It can also export XCode projects but not CLion / QTCreator. Maybe these
IDE can import a sln or make file?

The thing is, at the moment, only the netimgui library can be compiled
cross-platform and I actually expect to usually just add the sources files
to their existing Dear ImGui project. The samples and the NetImgui Server
only have Windows support at the moment. The server can almost compile on
Linux with opengl, it just need a few HAL_ functions filled. For the
samples, it would be to have the Linux backend support that Dear ImGui
made, instead of using the Windows one.

Finally, the project generations only runs on Windows, so to have makefile
support, I was thinking of exporting the makefile in the 'Build' directory
and check-in it in to the depot (unlike the VS solutions)

**Comment by sammyfreg** [comment]
I see. As mentionned, while the NetImgui library can be compiled on
multiple platforms, the exe (samples, server) only have support of Windows
right now.

This means that being able to import a CMake file from a .sln, would still
not be enough to test on linux/mac.

**Comment by lemantisee** [comment]
Roger that!
